name: Delpoy to ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 16.171.36.185
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd next_test
            cd cicd

           


            # Load nvm for the current session (this is needed to use nvm in the CI environment)
            source ~/.nvm/nvm.sh
  
            # Use a specific Node version with nvm (make sure it's installed in EC2)
            nvm use 16
  
            # Verify npm is available
            npm -v

            # Install dependencies
            npm install
  
             # Run the app
            npm run dev
            


            
